### ISSUE TITLE
Allow user to edit friends handle details

### ISSUE THREAD

**Issue by hitesh96db** [raj454raj/stopstalk#15]
Your friend has a handle for Codechef and SPOJ, but doesn't have a handle for Codeforces. You convince him/her that Codeforces is awesome and a month later (s)he joins it, and so now, (s)he has a handle for Codeforces. Where do you add the new handle ?

**Comment by raj454raj** [comment]
Cool. I suppose you are considering this CUSTOM USER only ;)
